Zadanie 22.4
MiKraska/Spring-Web-Repository pull request #6
Opened 2020-02-14 12:44 UTC by MiKraska

2020-02-14 19:32 UTC, coder-msl requested changes

2020-02-14 19:32 UTC, hacker-msl commented on src/main/java/com/crud/tasks/domain/CreatedTrelloCard.java
> +//    private Badges badges;
nie trzymaj komentarzy w PR. Od tego jest wersjonowanie kodu.

2020-02-14 19:32 UTC, hacker-msl commented on src/test/java/com/crud/tasks/trello/client/TrelloClientTest.java
> +        );
skąd pomysł na takie formatowanie? tak jest w kursie?

2020-02-14 19:32 UTC, hacker-msl commented on src/test/java/com/crud/tasks/trello/client/TrelloClientTest.java
> +        );
skąd pomysł na takie formatowanie? tak jest w kursie?

2020-02-15 09:17 UTC, MiKraska commented on src/test/java/com/crud/tasks/trello/client/TrelloClientTest.java
> +        );
Tak, dosłownie skopiowane z kursu.

2020-02-15 09:17 UTC, MiKraska commented on src/test/java/com/crud/tasks/trello/client/TrelloClientTest.java
> +        );
Tak, tak jest w kursie.

2020-02-15 09:23 UTC, MiKraska commented on src/main/java/com/crud/tasks/domain/CreatedTrelloCard.java
> +//    private Badges badges;
Poprawione.

2020-02-16 12:43 UTC, merged